### PR TITLE
Updates iron to 0.5

### PR DESCRIPTION
**Pull request by mdaffin**
Simply updates the version numbers to allow it to work with iron version 0.5.X. Without it tries to pull in iron 0.4 along side 0.5 (since the project I am working on depends on 0.5) then fails to compile with

```
error[E0277]: the trait bound `iron_cors::CorsMiddleware: std::ops::FnOnce<(std::boxed::Box<iron::Handler + 'stat
ic>,)>` is not satisfied
```

Alternatively you can also change the required iron version to be `>= 0.4 < 0.6`, I am not sure if you want to match irons versioning or not.

### CODE REVIEW

File: .travis.yml [hunk 1]
```diff
@@ -1,7 +1,7 @@
 sudo: false
 language: rust
 rust:
-  - 1.9.0
+  - 1.11.0
```
Comment (dbrgn) [inline .travis.yml]: Do you know the reason for the version increase?

**Comment by dbrgn** [comment]
Thanks!

> I am not sure if you want to match irons versioning or not

I don't intend to :)

**Comment by dbrgn** [comment]
0.5.0 is now released to crates.io.
